### ISSUE TITLE
API提供的是HTTP和HTTPS通用的IP怎么设置呢

### ISSUE THREAD

**Issue by Mangofang** [find-xposed-magisk/go_proxy_pool#1]
我用快代理这边的API，在config.yml中设置好之后，程序完成了提取，当我访问HTTPS的网站时，并不会启用任何代理。因为我发现在data.json中它们的type都是HTTP。这种情况怎么解决，是识别问题吗。当我将Type改为HTTPS的时候，可以正常使用，IP是HTTP和HTTPS都可以使用的

**Comment by find-xposed-magisk** [comment]
访问部署服务器的 8111 或者 8112 ，程序会自动使用。
访问方式：

`┌──(x㉿localhost)-[~]
└─$ curl -x http://10.1.22.18:8111 http://myip.ipip.net
Get "http://myip.ipip.net/": read tcp 10.0.22.18:49068->120.46.215.52:7000: read: connection reset by peer
                                                                                                                
┌──(x㉿localhost)-[~]
└─$ curl -x http://10.1.22.18:8111 http://myip.ipip.net
当前 IP：120.194.4.157  来自于：中国 河南 郑州  移动
`

程序日志：


`代理验证中: 64     [GIN] 2024/01/18 - 03:13:01 | 200 |      67.948µs |  192.168.192.83 | GET      "/"
代理验证中: 135     2024/01/18 03:13:19 隧道代理 | HTTP 请求：http://myip.ipip.net/ 使用代理: 114.115.130.225:3128
代理验证中: 2     2024/01/18 03:13:48 隧道代理 | HTTP 请求：http://myip.ipip.net/ 使用代理: 114.115.130.225:3128
`
